### ISSUE TITLE
Pentium E5200 reported as vulnerable - false positive report (?)

### ISSUE THREAD

**Issue by schloegl** [speed47/spectre-meltdown-checker#104]
Pentium E5200 is reported as vulnerable, this seems to be a false positive for the following reason: 

- Pentium E series is not reported as vulnerable  by Intel
https://www.intel.com/content/www/us/en/architecture-and-technology/facts-about-side-channel-analysis-and-intel-products.html#4
- Pentium E#### is also not listed here
https://www.techarp.com/articles/intel-amd-arm-cpu-bug-4/
- And also the results with Spectr did not show a vulnerability (search for E5200 in)
https://github.com/crozone/SpectrePoC/issues/1

$ grep model /proc/cpuinfo 
```
model		: 23
model name	: Pentium(R) Dual-Core  CPU      E5200  @ 2.50GHz
model		: 23
model name	: Pentium(R) Dual-Core  CPU      E5200  @ 2.50GHz

```

**Comment by speed47** [comment]
Thanks for these informations, that's exactly what I need to be able to add a CPU model in the whitelist.

Can you try the `pentium_e` branch? Waiting for your confirmation before merging.

**Comment by schloegl** [comment]
I tried the pentium_e branch, and yes the status for "spectre variant 2" is reported as not vulnerable. This seems good.

**Comment by schloegl** [comment]
I'm still wondering about the "vulnerability" report on "spectre variant 1", the web sites mentioned above do not report a vulnerability on spectre1, shouldnot the report on "spectre variant 1" also show a "non-vulnerability" for this CPU model ? 

I do not know the correct answer, I'm just wondering.

**Comment by speed47** [comment]
Thanks, merged to master

**Comment by speed47** [comment]
About Variant 1, a very wide range of processors (not only Intel's) are vulnerable, even those who are not vulnerable to Variant 2 or Variant 3/Meltdown. I don't know with 100% certainty the correct answer either, and when this is the case the script always default to "vulnerable" (because the main purpose of the script is not to check whether your CPU is vulnerable or not, but whether the proper mitigations are in place on your system or not).
I already had previous reports of people saying that their Intel CPU was not listed by Intel as vulnerable in the official list, but that the PoCs were working. If we can get a Variant1 PoC test that reportedly doesn't work on E5200 but works on others, I'll update the script accordingly!

**Comment by schloegl** [comment]
Running the test meltdown-exploit reports that the platform is still vulnerable - see 
 https://github.com/paboldin/meltdown-exploit/issues/19 ^F E5200

I do not know which vulnerability (spectre 1, 2 or meltdown) is exploited in this test, but one might revert the clearance for the Pentium E series in this check.

**Comment by speed47** [comment]
The exploit you linked is meltdown. So it seems E5200 is vulnerable to variant 2 only (as per the previous test). Change done in 6e544d6055e917778a6e6be8189fdd2a36aa4e27. Thanks.
