### ISSUE TITLE
Spectre v2 checks too optimistic? [skylake]

### ISSUE THREAD

**Issue by mittwinter** [speed47/spectre-meltdown-checker#111]
First of all, thanks for this awesome checker, however, after some research it seems to be overly optimistic for Spectre v1 and v2 in 2 cases (yet in one of them, only probably):

1. According to [retpoline-underflow] Skylake and above (i.e., Core i-6xxx and above) are still vulnerable to a variant of Spectre v2 - even with IBRS support in kernel - and need further patches which are currently still under development. Thus, just checking IBRS kernel support is probably not sufficient for these processers.
2. The threshold of the heuristic for Spectre v1, counting LFENCE opcodes, could be too low, see report in [lfence-linux-3.10], though the post is a little light on system details and thus cannot be verified easily.

[retpoline-underflow] https://www.phoronix.com/scan.php?page=news_item&px=RETPOLINE_UNDERFLOW
[lfence-linux-3.10] https://forums.gentoo.org/viewtopic-p-8174114.html#8174114

On a sidenote, I'm also wondering how the LFENCE heuristic relates to custom compiled kernels with lots of kernel options being disabled and thus a smaller compiled-in codebase.

**Comment by speed47** [comment]
Hello!

1. I'm following the LKML as much as I can, and indeed things are going pretty fast. There's a lot of discussion and all the patches that are floating won't all get merged. However I see from an email that was sent yesterday that this one might make it ( https://marc.info/?l=linux-kernel&m=151674719914506&w=2 ). I'll start a branch to work on that. The rationale would be : if I detect that the CPU is Skylake *and* the kernel didn't add the rsb_underflow feature in cpuinfo, it means that the protection won't be okay if the kernel is relying on retpoline for variant2 for IBRS. Thanks for the pointer.

2. The variant 1 detection, when the `/sys` vulnerability hierarchy is not there (as this is the case on most distros / backported kernels), is quite difficult. RedHat sait they fixed variant 1, and I looked at their source code : they did add a bunch of LFENCE opcodes "a bit everywhere", at proper places in the kernel. That's how I attempt to detect that, because AFAIK there's no other way at this stage (again, when the `/sys` hierarchy is not there, on vanilla kernels it is). I know there can be false positives and false negatives with this test : either you have a LFENCE-filled kernel but with a minimal compilation you're under the threshold (false negative), or you don't have a LFENCE-filled kernel but are compiling most of the stuff not as modules but directly in the kernel, hence crossing the threshold (false positive). Still, it works on most of the usual cases, but it's clearly not perfect and this is why I've added the comment about the heuristic way of detecting variant 1 mitigation in the absence of `/sys` hierarchy.

**Comment by knweiss** [comment]
@mittwinter Regarding 1) Maybe I'm misunderstanding your comment but my understanding of the situation is different:

The software-only **retpoline** mitigation alone is not sufficient on Skylake+ - IBRS, however, is (for the kernel). (I.e. the retpoline mitigation itself is just an optimized alternative for the more expensive IBRS mitigation. And on CPUs older than Skylake it is good enough as a IBRS replacement. On Skylake+ it needs additional help for cases like the RSB though as these CPUs have even more aggressive speculation.)

Here's  a quote of [David Woodhouse's explanation](https://lkml.org/lkml/2018/1/22/598) with more the details:

> The third feature (IBRS) is more complicated. It's designed to be
> set when you enter a more privileged execution mode (i.e. the kernel).
> It prevents branch targets learned in a less-privileged execution mode,
> BEFORE IT WAS MOST RECENTLY SET, from taking effect. But it's not just
> a 'set-and-forget' feature, it also has barrier-like semantics and
> needs to be set on *each* entry into the kernel (from userspace or a VM
> guest). It's *also* expensive. And a vile hack, but for a while it was
> the only option we had.
> 
> Even with IBRS, the CPU cannot tell the difference between different
> userspace processes, and between different VM guests. So in addition to
> IBRS to protect the kernel, we need the full IBPB barrier on context
> switch and vmexit. And maybe STIBP while they're running.
> 
> Then along came Paul with the cunning plan of "oh, indirect branches
> can be exploited? Screw it, let's not have any of *those* then", which
> is retpoline. And it's a *lot* faster than frobbing IBRS on every entry
> into the kernel. It's a massive performance win.
> 
> So now we *mostly* don't need IBRS. We build with retpoline, use IBPB
> on context switches/vmexit (which is in the first part of this patch
> series before IBRS is added), and we're safe. We even refactored the
> patch series to put retpoline first.
> 
> But wait, why did I say "mostly"? Well, not everyone has a retpoline
> compiler yet... but OK, screw them; they need to update.
> 
> Then there's Skylake, and that generation of CPU cores. For complicated
> reasons they actually end up being vulnerable not just on indirect
> branches, but also on a 'ret' in some circumstances (such as 16+ CALLs
> in a deep chain).
> 
> The IBRS solution, ugly though it is, did address that. Retpoline
> doesn't. There are patches being floated to detect and prevent deep
> stacks, and deal with some of the other special cases that bite on SKL,
> but those are icky too. And in fact IBRS performance isn't anywhere
> near as bad on this generation of CPUs as it is on earlier CPUs
> *anyway*, which makes it not quite so insane to *contemplate* using it
> as Intel proposed.
> 
> That's why my initial idea, as implemented in this RFC patchset, was to
> stick with IBRS on Skylake, and use retpoline everywhere else.

**Comment by speed47** [comment]
This is my understanding too. To try to summarize a bit, to mitigate Variant 2, either

- You enable IBRS + IBPB (hardware support thu CPU microcode required for both). This works for all CPUs, as long as the microcode is updated.
or
- You don't have a Skylake CPU, you compile the kernel with the RETPOLINE option, with a retpoline-aware compiler. You also need IBPB to have a complete protection (but IBRS is not needed).
- You have a Skylake CPU, you compile the kernel with the RETPOLINE option, with a retpoline-aware compiler, a kernel that is recent enough to have the RETPOLINE_UNDERFLOW feature that is needed to have a completely functional retpoline for these CPUs.  You also need IBPB to have a complete protection (but IBRS is not needed).

In addition to all that, STIBP might or might not be a good addition, there's not yet a real consensus over it.

**Comment by mittwinter** [comment]
@knweiss @speed47 Thanks for the clarification on the details. I found the cited LKML mail after I reported this issue here, and until then all sources that I found read like IBRS is not sufficient on Skylake and above.
So far, the sources I read even diverge regarding the affected generations: Sometimes it's "Skylake" sometimes "Skylake and above" (e.g., the cited mail by David Woodhouse just mentions Skylake, other sources like phoronix also "newer generations") - so I am still not sure whether Caby Lake and Coffee Lake also need retpoline_underflow protection (if one doesn't want expensive IBRS).

**Comment by knweiss** [comment]
@mittwinter Skylake, Kabylake, Coffeelake, and Cannonlake are all CPUs based on the Skylake **microarchitecture** and [affected](https://security-center.intel.com/advisory.aspx?intelid=INTEL-SA-00088&languageid=en-fr). I.e. when mails mention "Skylake" they (_probably_) reference the microarchitecture, not only its first incarnation.

(Icelake will be the next microarchitecture.)

**Comment by speed47** [comment]
Closing this.
The `--paranoid` option can be used to require IBPB in all cases to deem Variant 2 as mitigated.
