### ISSUE TITLE
--live vs --no-sysfs   Which one is right? (for 'Spectre Variant 1')

### ISSUE THREAD

**Issue by xftroxgpx** [speed47/spectre-meltdown-checker#114]
Which one should I believe?

Live says I'm vulnerable:
```
$ ./spectre-meltdown-checker.sh 
Spectre and Meltdown mitigation detection tool v0.32
...
CVE-2017-5753 [bounds check bypass] aka 'Spectre Variant 1'
* Mitigated according to the /sys interface:  NO  (kernel confirms your system is vulnerable)
> STATUS:  VULNERABLE  (Vulnerable)
```

LFENCE checking says I'm not:
```
$ ./spectre-meltdown-checker.sh --no-sysfs
CVE-2017-5753 [bounds check bypass] aka 'Spectre Variant 1'
* Checking count of LFENCE opcodes in kernel:  YES 
> STATUS:  NOT VULNERABLE  (79 opcodes found, which is >= 70, heuristic to be improved when official patches become available)
```

Tested latest commit of the script: d1c1f0f0f0e9fa69206605c4d38f0bcc9fa55ff4
with kernel: Linux z5 4.15.0-rc9-g0c5b9b5d9adb #178 SMP PREEMPT Wed Jan 24 20:04:41 CET 2018 x86_64 GNU/Linux

**Comment by speed47** [comment]
There is not yet a mitigation for Variant 1 in vanilla/upstream Linux kernel. However, some Linux distros have already implemented one (RedHat at least), by adding LFENCE opcodes at the proper places in the kernel source code. For now there is no other way to detect that than counting the number of occurences of those opcodes. The threshold of 70 is empiric, I see you are above but not from a big margin, so this is probably a false positive, I might set a higher threshold to avoid that (RedHat kernels have a count higher than 100). Did you compile this kernel yourself ? It can happen if you enabled a lot of features to be compiled in (not as modules).
The live mode without the --no-sysfs also checks what the kernel has to say about the mitigation (this is not available on all kernels). When the kernel has something to say, this is almost always correct, which is why it's the default when available. In the case of Variant 1, this is always correct because for now the "Vulnerable" status is hardcoded (There is no official mitigation yet). So in a nutshell, you're almost certainly vulnerable, but almost everybody is (except some vendors kernels)

**Comment by xftroxgpx** [comment]
Thank you, that all makes sense now.

> Did you compile this kernel yourself ? It can happen if you enabled a lot of features to be compiled in (not as modules).

I did, here's the [.config](https://github.com/xftroxgpx/a3/blob/cb38308ec59cab676baf0f518f1a6dc1f45b4fe9/system/Z575/OSes/3archlinux/on_baremetal/filesystem_now/archlinux/home/xftroxgpx/build/1packages/kernel/linuxgit/makepkg_pacman/linux-git/src/linux-git/.config#L1)

>The threshold of 70 is empiric, I see you are above but not from a big margin, so this is probably a false positive, I might set a higher threshold to avoid that (RedHat kernels have a count higher than 100)

I thought I'm lower because I tailored my .config specifically for my laptop, thus having removed a lot of stuff that it doesn't need. It was actually like `44` before switching to `-rc9`.

**Comment by xftroxgpx** [comment]
I double checked:
I had 58 opcodes in my previous kernel, which was: linux-git-4.15rc8.r72.g8cbab92dff77-1-x86_64.pkg.tar
but that one wasn't compiled with the retpoline aware gcc (if that makes any difference)

**Comment by xftroxgpx** [comment]
Here's the LFENCE count for two other stock (archlinux) kernels, listed by package name:

<details><summary>linux-lts</summary>

```
Linux z5 4.9.78-1-lts #1 SMP Tue Jan 23 21:41:02 CET 2018 x86_64 GNU/Linux
ArchLinux package: local/linux-lts 4.9.78-1
Name            : linux-lts
Version         : 4.9.78-1
Build Date      : Tue 23 Jan 2018 09:42:57 PM CET
Validated By    : Signature
```

```
CVE-2017-5753 [bounds check bypass] aka 'Spectre Variant 1'
* Checking count of LFENCE opcodes in kernel:  NO 
> STATUS:  VULNERABLE  (only 62 opcodes found, should be >= 70, heuristic to be improved when official patches become available)
```
</details>

<details><summary>linux</summary>

```
Linux z5 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
Name            : linux
Version         : 4.14.15-1
Build Date      : Tue 23 Jan 2018 10:53:27 PM CET
Validated By    : Signature
```

```
CVE-2017-5753 [bounds check bypass] aka 'Spectre Variant 1'
* Checking count of LFENCE opcodes in kernel:  NO 
> STATUS:  VULNERABLE  (only 63 opcodes found, should be >= 70, heuristic to be improved when official patches become available)
```
</details>

I'm guessing then, you were right, I chose to compile some usual modules(eg. radeon) into kernel (ie. `y` not `m`) which increased my LFENCE count.
