### ISSUE TITLE
Arch Linux Hardened kernel reports not vulnerable but CPU vulnerability reports as being vulnerable

### ISSUE THREAD

**Issue by ejbolt** [speed47/spectre-meltdown-checker#123]
![image](https://user-images.githubusercontent.com/21202046/35594212-f2898cd0-05d7-11e8-9e65-d21c4e8057b4.png)

Arch Linux hardened kernel 4.14.15-1 on Intel Core i7-6700HQ @ 2.60GHz

I'm a bit confused on the output of the script, as it reports my XPS as not vulnerable in the sections for variants 2 & 3, but up above it is reported as vulnerable.  Is there something I'm missing in what the above statuses represent or is this an error.  Screenshot attached.

**Comment by cement-head** [comment]
Run as root (sudo)

**Comment by ejbolt** [comment]
Whoops, let me update the screenshot
Same results when run as sudo

**Comment by ejbolt** [comment]
Any ideas on why there's still one Unknown value?

**Comment by speed47** [comment]
Yes, this is a tiny bug in the v0.33 release that has been fixed in the commit that follows it. You can mentally replace this "unknown" by a "no" : if the arch_capabilities MSR is not exposed, then the RDCL_NO bit is never set. Don't expect any CPU to have this bit set before a couple of months or maybe even 2019 (CPUs that will advertise the fact that they're not vulnerable to meltdown).
I didn't want to release another version right after just for that, but it'll be in v0.34 that should be out by tomorrow.

**Comment by ejbolt** [comment]
Excellent, I just wanted to check if it was a bug or if I had to do something manually on my machine.  You've done excellent work on this so please don't take it as a criticism. :)
This is an awesome script.
