### ISSUE TITLE
False negative?

### ISSUE THREAD

**Issue by nomadmzl** [speed47/spectre-meltdown-checker#157]
I run the script and I get:

![script](https://user-images.githubusercontent.com/27929953/36939166-a8f07192-1efa-11e8-81b5-25eb2c476091.png)

CVE-2017-5753, CVE-2017-5715, CVE-2017-5754  seems to be fixed here.

But when I run `cat /proc/cpuinfo`, I see Spectre v1 and v2 in the bugs section: 

![cpu info](https://user-images.githubusercontent.com/27929953/36939173-bfa8a440-1efa-11e8-9034-14feaae5d3dd.png)

So I run: `grep . /sys/devices/system/cpu/vulnerabilities/*`: 

![3](https://user-images.githubusercontent.com/27929953/36939246-9e09c1ec-1efb-11e8-96f7-7c070cb3972f.png)

So which one is telling the true? am I getting wrong the `cat /proc/cpuinfo` and  `grep . /sys/devices/system/cpu/vulnerabilities/*` purpose?

Bye!

**Comment by speed47** [comment]
They're all telling the truth, but from your message I understand that you're a bit confused by what you're seeing in `cpuinfo` on the "bugs" line. This line only means that your CPU model is vulnerable to these bugs. It doesn't say wether there is a mitigation active or not, this information, however, is available under the `/sys` hierarchy as you've correctly seen. The checker script does use this information when it's available (not the case on all kernels); so it also reports that you're not currently vulnerable because the mitigations are active.
Does that seem more clear ?

**Comment by nomadmzl** [comment]
Bright clear, thank you!
