### ISSUE TITLE
retpoline+IBPB is NOT? needed to mitigate the vulnerability on some CPUs

### ISSUE THREAD

**Issue by kuzetsa** [speed47/spectre-meltdown-checker#181]
BTI (CVE-2017-5715) mitigation: retpoline alone, *without IBPB* might be acceptable  
... *at least on some CPUs*

in particular:$ cat /sys/devices/system/cpu/vulnerabilities/spectre_v2 
```
Mitigation: Full generic retpoline
```
... for some CPUs, acceptable mitigation (*with minimal overhead penalties*) can be had from an updated compiler, kernel, and system-wide userland rebuild to enable retpoline. 
 (*and/or update all premade binary packages, as appropriate*)

IBPB is painfully slow, and in cases where intel's testing hasn't shown it to be required, IBPB is a senseless penalty for little (*if any*) gains compared to a retpoline-only BTI mitigation.

---

This is a secondary source (**not** *directly from intel*):

https://github.com/marcan/speculation-bugs/blob/master/README.md#cpu-vendor-response

> [ *Alternatively, Intel is recommending retpolines for BTI, especially on current processors where that may be faster than the microcode patches for IBPB. Retpolines also require a microcode patch on Broadwell and newer CPUs* ]

---

I tried tracking down the specific quote where intel made the recommendation to use retpoline without IBPB for performance reasons, but gave up after 30 minutes of digging.

**Comment by Matthew-Bradley** [comment]
I'd be really interested to know whether this is the case. I've got a lot of machines that are frustraightingly *just* outside the window of what Intel has decided they want to provide microcode updates for. (a LOT of institutions haven't bought all new computers in the last five years)

I'm also curious (just for a moment, speed be damned) if it's possible to implement the equivalent of IBPB for older machines that Intel has recently decided never to look at. I'd speculate (get it?) that if an attacker can stuff the branch predition buffer by repeatedly jumping, why can't we? I understand it'd be slow as all hell, but might provide a fallback for those left in the lurch.

**Comment by orachas** [comment]
Oracle has a useful blog post on this subject:
https://blogs.oracle.com/linux/an-update-on-retpoline-enabled-kernels-for-oracle-linux-v2

The author links to this Intel document:
https://software.intel.com/sites/default/files/managed/1d/46/Retpoline-A-Branch-Target-Injection-Mitigation.pdf

In this document, I see:

"5.1 Processor Models - Retpoline is known to be an effective branch target injection (Spectre variant 2)
mitigation on Intel processors belonging to family 6 (enumerated by the CPUID
instruction) that do not have support for enhanced IBRS. On processors that support
enhanced IBRS, it should be used for mitigation instead of, or in combination with,
retpoline."

I also understand that some peripheral devices include (x86) firmware that may be executed by the kernel which might use branching that is vulnerable to speculative attack.

**Comment by Matthew-Bradley** [comment]
Yeah, I vaugely recall reading that some of the microcode-supplied features were being used to protect against speculation inside of calls to firmware. (when it comes to spectre/meltdown, good luck getting support/patches for that stuff)

Speaking of CPUs that won't receive IBRS or IBPB microcode updates and may not need them, I have an AMD Phenom-based machine which is reported to have "Full AMD Retpoline" yet is still "vulnerable" because it lacks IBPB. Does AMD plan to release/has released microcode updates to introduce these features? Are IBRS and IBPB concepts that even apply to AMD CPUs?

I imagine the above speculation-in-firmware and other issues related to spectre v2 must at least apply to AMD a little.

**Comment by kuzetsa** [comment]
> I'd be interested if anyone's looked at a slow software IBRS or IBPB, but all signs I've seen point to it being a microcode-only thing.

I wasn't able to mentally parse that sentence, @Matthew-Bradley 

I've tested the intel microcode update which is available for one of my systems which is NOT on the list of CPUs: "*this one absolutely requires IBPB because retpoline-only is ineffective*" and the performance hit (increased latency) was measurable.

If I get the time I'll shuffle around and cook the data into a human-readable report which isn't nearly as opaque as the raw data.

**Comment by orachas** [comment]
To be specific, the 0.35 version of the script tested this file:

# cat /sys/devices/system/cpu/vulnerabilities/spectre_v2
Mitigation: Full AMD retpoline

In 0.35, if the word "Full" was found here, then the script reported "Not Vulnerable" with the following test:

grep -qw Full /sys/devices/system/cpu/vulnerabilities/spectre_v2; then
...pstatus green YES "kernel reports full retpoline compilation"

This reporting was changed on April 4th with a commit titled "feat: rework Spectre V2 mitigations detection w/ latest vanilla & Red Hat 7 kernels" where the script began demanding IBPB. I don't see any commentary on why this was done. I would like to know more detail on the reasons for this change, and who was involved.

On another subject, the Oracle blog post in my last comment also mentions 3rd-party kernel modules. These must also be prepared with a retpoline-aware compiler - otherwise they can be successfully targeted in a speculative attack, and a dmesg fragment is provided that specifically warns of this condition. Non-retpoline modules join device x86-firmware that the kernel executes as vectors to reintroduce the vulnerability.

I am not convinced that "Full AMD retpoline" is now once again completely vulnerable, and it appears to me that all the code in my distro's kernel package is safe. I would like to know how to identify unsafe peripherals, activities, and what countermeasures are possible.

**Comment by Matthew-Bradley** [comment]
To rephrase: As far as I know, nobody has looked at an alternative (even a horifyingly slow one) to the requirement that you have IBPB in microcode to go along with retpoline. I whould have thought it would be possible but nothing specifically points to this being possible. (if an attacker can do repeated jumps to poison the buffer, then instead of clearing it on context-switch with IBPB I would have thought we could do the same jumping around to un-poison it)

To the best of my understanding, being a non-expert in this stuff:
IBPB is needed because an attacking program can do a bunch of jumping within it's own memory space, which then results in speculation in another process that runs some "gadget" piece of code that wouldn't normally run (and leaks data). Recompiling the Kernel with retpoline protects gadgets from being found in the kernel. Recompiling web browsers prevents gadgets being found in web browsers.  HOWEVER, because a lot of software out there isn't compiled with retpoiline, an attacker could still do a bunch of jumping and trigger a gadget in some other program that doesn't have retpoline. It could also do it before a call to some firmware, which almost certainly won't have retpoline and could be full of "gadgets" that will leak data available to the firmare's privledge level. By having IBPB, you can clear the poisoned buffer before entering software that doesn't have retpoline, including firmware.

All of this comes with the asterisk though that this is just what I've been able to understand from what I've read on the subject. If a kernel developer who wrote the protections wants to chime in, I'd be really grateful.

**Comment by kuzetsa** [comment]
@orachas - Ah! Good catch. de02dad90945930e0ec489dca6257fd59e060b55 is a major rewrite, and this may just be a regression / mistake (*unintended consequence from the logic changes*).

**Comment by Matthew-Bradley** [comment]
For reference, some of the best descriptions I've found:
https://lkml.org/lkml/2018/1/4/622
and specifically regarding KVM:
https://lkml.org/lkml/2018/2/1/638

**Comment by kuzetsa** [comment]
@Matthew-Bradley yeah, that stuff looks right to me. Those details are correct.

1. [PATCH v6 2/5] KVM: x86: Add IBPB support (*early january*) predates the wide availability and deployment of mature retpoline-type compilers. Note the lack of any mention for retpoline-type fixes.

2. [PATCH v6 2/5] KVM: x86: Add IBPB support (*Feb 1st) mentions a case of a CPU where IBPB is required (*skylake in particular, is known to be an example*), but also specifically mentions a usage case where retpoline is an alternative mitigation strategy which doesn't involve IBPB, but again mentioning the skylake exception.

I was careful when I file this issue to use qualifying language: "on some CPUs", as skylake is on the list which is known to require IBPB.

**Comment by speed47** [comment]
Thanks for all your research.

I added IBPB as a requisite to "NOT VULNERABLE" on variant 2 after seeing how Red Hat changed the default protection in their latest kernels.
You can see here https://access.redhat.com/articles/3311301#indirect-branch-prediction-barriers-ibpb-10 that they automatically enable IBPB when the user enables Retpoline. This is also the default.

In the vanilla kernel, IBPB is now also enabled in any case when it's available, including when the kernel has been compiled with retpoline (vanilla kernel actually doesn't support IBRS appart from the specific IBRS_FW for the firmware code):
https://elixir.bootlin.com/linux/v4.16.2/source/arch/x86/kernel/cpu/bugs.c#L286

So it would seem that the code implies that IBPB is not useless with retpoline, quite the contrary.

However it does mean that a lot of CPUs that don't yet (or never will) have a microcode update will get VULNERABLE with no way to fix it. To avoid freaking out people, I could create a `--paranoid` to check for IBPB Spectre 2 and ignore it otherwise...

I'd like to get this sorted before releasing v0.37.

**Comment by Matthew-Bradley** [comment]
@kuzetsa Are you sure you're not confusing IBRS and IPBP? My understanding is that skylake needs IBRS, because it will occasionally fall back to the poisoned buffer on returns, so retpoline is insufficient by itself. Aparently "retpoline underflow" now fixes this and IBRS is no longer necessarily needed on skylake.

However, IBPB is still needed everywhere to protect against exploitation of software/firmware/ect that has not been compiled with retpoline. In the case of firmware, it's entierly possible it never will be.

**Comment by orachas** [comment]
How about the following warning:

Retpoline *WITHOUT* IBPB - modules, firmware, and BIOS/ACPI/UEFI may introduce vulnerable code

I read a quick discussion of [when] the OS executes various types of BIOS code here:

https://superuser.com/questions/462314/what-are-the-functions-of-the-bios-while-the-operating-system-is-running

**Comment by kuzetsa** [comment]
@Matthew-Bradley You linked https://lkml.org/lkml/2018/2/1/638 and it mentions IBPB (*no mention of IBRS*) - I'm a bit confused by your question, honestly.

@speed47 - yeah, IBPB covers things which won't otherwise be able to protect themselves using cheaper (less overhead) retpoline-based compilation.

Like - maybe as an alternative to the more generic: "vulnerable" message, when "full retpoline" is detected in the kernel but IBPB is **NOT** detected, a brief notice that sensitive userspace processes need retpoline mitgations:

"unless IBPB is enabled, older binaries built without a retpoline-type compiler are vulnerable to BTI (CVE-2017-5715)  attacks"  
... or something like that.

@orachas - yeah, binary blob firmware which can't be audited for security is never trustworthy IMO :(

**Comment by Matthew-Bradley** [comment]
That link was mostly in reference to IBPB
There's more info (including IBRS) here as well: https://github.com/speed47/spectre-meltdown-checker/issues/111
Particularly in the excerpt from the kml.

Reading over the code @speed47 linked, it seems IBRS is also used to protect firmware (X86_FEATURE_USE_IBRS_FW). I don't know what's going on with AMD in that case though, since I've only heard about IBPB from them.

**Comment by speed47** [comment]
AMD plans to implement IBRS for at least some CPUs, at they have published information about how to detect an IBRS-capable AMD processor (a different CPUID bit than Intel). This CPUID bit is already checked by the script, but I haven't seen any AMD CPU with it yet.

**Comment by kuzetsa** [comment]
@Matthew-Bradley I think IBRS is only available on newer intel CPUs, so I believe anything older than ... skylake? won't have IBRS.  
(*I don't recall IBRS being part of the microcode updates for 1.3ghz sandybridge-based "dualcore i3 potato" in my ultrabook*)

IBRS in particular has performance hits which torvalds described as a "vile hack", and my own hot take on the intel microcode this agrees with that kind of criticism:

Compared to compiler-level changes, one-size-fits-all microcode "fixes" are a blunt instrument which breaks optimizations for the sake of security. (*and I have some firsthand test data on IBPB. it's quite bad for my usual workloads. haven't got relevant hardware to test IBRS though*)

It's possible that a future version of microcode-type spectre mitigation(s) will be computationally **LESS** expensive (*and able to be managed with a fine-grained approach by the kernel*) compared to compiler-level (*still optimized*) retpoline.

Seems more likely that a speedup-type microcode will be possible if it's selectively managed by the "IL to assembly" stage in optimizing compilers (*or whichever other level that would need to happen at*). I rather doubt "the good stuff" isn't coming to my sandybridge potato though. My only choices are retpoline or major peformance hits. 
"Maybe some day" [tm]

---

^ getting a bit offtopic.

thanks for looking at the nuance & considering a rework the IBPB-related notice(s), @speed47

**Comment by orachas** [comment]
Intel originally said that they would only produce new microcode for CPUs manufactured within the last 5 years.

They have since widened that net, and some older CPUs will get firmware when convenient, so IBPB might appear on older systems.

https://it.slashdot.org/story/18/04/04/1333252/intel-says-some-cpu-models-will-never-receive-microcode-updates

I have Core 2 Duos and Athlons that will never get it.

**Comment by Matthew-Bradley** [comment]
@orachas The article you've linked would seem to support the opposite: That intel origionally intended to provide microcode updates furthur back, but have now issued a "stop" for anything older than five years.

https://rcpmag.com/blogs/scott-bekker/2018/03/intel-meltdown-spectre-updates-done.aspx
and more recently (april 4th):
https://hexus.net/tech/news/cpu/116885-intel-halts-microcode-patch-development-230-cpus/
says that intel has stopped working on microcode updates. Do you have a link to a more up-to-date release that says otherwise?

**Comment by orachas** [comment]
I just googled "microcode stopped" and this is the first hit:

http://www.hexus.net/tech/news/cpu/116885-intel-halts-microcode-patch-development-230-cpus/

"We've now completed release of microcode updates for Intel microprocessor products launched in the last 9+ years that required protection against the side-channel vulnerabilities discovered by Google Project Zero."

**Comment by Matthew-Bradley** [comment]
Ah, yes. I missed that bit added to the bottom from a separate source. Not sure how much I trust it though.

Googleing around, a bunch of places have the more complete quote:
"We've now completed release of microcode updates for Intel microprocessor products launched in the last 9+ years that required protection against the side-channel vulnerabilities discovered by Google Project Zero," Intel said in a statement sent to us. "However, as indicated in our latest microcode revision guidance, we will not be providing updated microcode for a select number of older platforms for several reasons, including limited ecosystem support and customer feedback."

**Comment by speed47** [comment]
Just pushed the `ibpb` branch with the following change:

IBPB is not required to get "not vulnerable" for Variant 2, however a warning will be shown below the status. If `--paranoid` is specified IBPB is required for retpoline or IBRS to be considered as a complete Variant 2 mitigation.

**Comment by kuzetsa** [comment]
the spirit of #181 - ["... IBPB is NOT? needed..."]:

I feel that the microcode "fix" (*rather, its current blunt instrument incarnation*) from intel is contentious, and it nearly comes across as ~~disingenuous~~ (*err, dubious? some better word probably.*) for the message to still be present (*and red*) when --paranoid is disabled:

[speaking for myself / my views]  
the new warning message (*current wording as-of: 223f5028dfa684dae3c4aabdd1d3aeb333992f42*) sends a mixed message by showing the nag when --paranoid is disabled. As for the wording, I think ...

~~${OpinionOmmited}~~

... 0919f5c236cbf793e098877717011fd8cf35b7cf contains several (~~debatable?~~) assertions which, I suspect, are likely the views of a particular distro, security team, or person, rather than the fruits of a democratic consensus. It's a big commit, and full of a lot of words, and I would've used different words if I wrote the explanation? Either way is fine.

Semi-unrelatedly, the wording for --disclaimer is great:

```
Please also note that for Spectre vulnerabilities, all 
software can possibly be exploited, this tool only 
verifies that the kernel (which is the core of the system) 
you're using has the proper protections in place. 
Verifying all the other software is out of the scope of 
this tool. As a general measure, ensure you always have 
the most up to date stable versions of all the software 
you use, especially for those who are exposed to the 
world, such as network daemons and browsers.
```

**Comment by Matthew-Bradley** [comment]
@kuzetsa All of the microcode patches are quite a bit more mature by this point, with Intel no longer choosing to patch any more chips. While early patches were plauged with issues, they're now probably as finalized as they're going to be considering how difficult microcode patches can be. They're also important enough to coverage that AMD released an update this week (4/10/18): https://www.amd.com/en/corporate/security-updates

As @speed47 noted, IBPB is getting enabled in the vanilla kernel even with retpoline in place. If it's getting used by the kernel for protection then I definitely think that it's something to allways warn about when it's not there. That's why I agree with @speed47 's above reasoning to allways include a warning, but only change the toplevel status when "paranoid". I think that's a good compromise, similar to informing when the performance impact of PTI will be not be reduced.

While I'd like to see the availability of IBRS and IBPB geting noted because of all their various uses (like mitigating firmware speculation or with KVM) those are things that may or may not fall under "core of the system" protection.

**Comment by Matthew-Bradley** [comment]
One other thing to look into is an article I just found going through the various AMD mitigation strategies:
https://www.techarp.com/guides/amd-spectre-mitigation-guide/

What might be relavent to this this thread is that it's stated that AMD has mitigations you can implement that are software+hardware OR software only, though I've not seen any speak of software only naywhere else, and the link to their release in my previous comment would seem to contradict that, considering they speak exclusively of a combined approach.

**Comment by kuzetsa** [comment]
> All of the microcode patches are quite a bit more mature by this point, with Intel no longer choosing to patch any more chips. [...]

@Matthew-Bradley nah, that's not true - they only discontinued microcode further development for very old CPUs. Lots of the modern CPUs are still getting microcode updates.

**Comment by Matthew-Bradley** [comment]
@speed47 I came across this which would seem to shed some light on some above things: https://lkml.org/lkml/2018/3/20/295
Folowing the mail thread, there's this on the subject of userspace-to-userspace mitigation without IBPB (seems it requires a retpoline userspace, since RSB stuffing only affects RETs, if I'm reading the latter messages right):
"The assumption thus far (good or bad) is that everything will get a microcode update.  I actually don't know for sure if RSB manipulation is effective on old microcode before Skylake.  I'm pretty sure it has not been documented publicly."

It seems to me that there is a little bit of work being done on "what do you do if you don't have updated microcode" but reading all the messages it seems to me it's from the standpoint of "IBPB/IBRS are slow" Still, you might draw your own conclusions. At any rate, it's something I found that seems interesting.

**Comment by orachas** [comment]
If/when I have control over a critical application, I will sink it into a chroot() if possible, either explicitly or through systemd-nspawn.

This is obviously a challenge with an Oracle database instance, but it can be done. I wish the browsers would do it.

POSIX chroot() has been with us since Bell Labs version 7. Everyone whines that it's too hard, which should stop. I wonder what Tails does.

**Comment by Matthew-Bradley** [comment]
Looking WAAAY back: https://lkml.org/lkml/2018/1/22/598
"The early part of the series adds the new feature bits and detects when
it can turn KPTI off on non-Meltdown-vulnerable Intel CPUs, and also
supports **the IBPB barrier that we need to make retpoline complete**. That
much I think we definitely *do* want. There have been a bunch of us
working on this behind the scenes; one of us will probably post that
bit in the next day or so."

So now I wonder how true this still is (that IBPB is needed for complete retpoline), especially if you've got a bunch of userspace stuff compiled with retpoline.
