### ISSUE TITLE
IBPB is considered as a good addition to retpoline for Variant 2 mitigation, but your CPU microcode doesn't support it

### ISSUE THREAD

**Issue by psposito** [speed47/spectre-meltdown-checker#183]
I am running Arch Linux 4.16.2-2-ARCH with AMD Phenom(tm) II X4 955 CPU...
Before updating to the latest version, I had never such a report from it...

**Comment by psposito** [comment]
So, an update for amd-ucode is needed.....
Correct?

**Comment by speed47** [comment]
Yes, AMD will release microcode updates to some (not all) of their CPUs.
I think some versions of their latest ZEN-architecture-based (EPYC / Ryzen) CPUs did receive an update, I don't know what their release schedule is. However, given your CPU model, it's uncertain you'll have a microcode update. That's why it's "just" a warning and doesn't make the Variant 2 test fail (unless you've used `--paranoid`), as a lot of CPUs will just never get an update and will have to rely on just retpoline (which is already way better than nothing)

**Comment by psposito** [comment]
Thanks..
I installed the latest firmware-git version 20180416, and I am still getting the same message....

**Comment by psposito** [comment]
Shifted on Manjaro,  kernel 4.16.2-1-MANJARO and linux-firmware  20180402.8c1e439-1 release.....
After running the script, everything looks ok..
Thanks!

**Comment by speed47** [comment]
Most probably AMD will not update the firmware for their Phenom, as this is a not-too-recent model (don't bother, Intel does the same...).
So, closing it for now, as there's nothing I or you can do about it, unfortunately :(
Don't hesitate to reopen if needed, for example if AMD finally releases the firmware for your CPU, and the script doesn't detect it!
