### ISSUE TITLE
Support for L1 Terminal Fault (L1TF)

### ISSUE THREAD

**Issue by crepererum** [speed47/spectre-meltdown-checker#229]
CVEs:
- CVE-2018-3615
- CVE-2018-3620
- CVE-2018-3646

References:
 - https://phoronix.com/scan.php?page=news_item&px=L1-Terminal-Fault
 - https://www.youtube.com/watch?v=n_pa2AisRUs
 - https://blog.ubuntu.com/2018/08/14/ubuntu-updates-for-l1-terminal-fault-vulnerabilities
 - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=958f338e96f874a0d29442396d6adf9c1e17aa2d&anz=show

The Linux PR gives a nice overview, also regarding the possible checks that `spectre-meltdown-checker` could execute and advices it could provide.

**Comment by speed47** [comment]
The commit is very detailed indeed this time.
I'll implement this next. Detection of vulnerable CPUs will come first, this should be easy to implement given the tools already implemented in the script. Then I'll implement mitigation detection.

**Comment by knweiss** [comment]
Some more references:
   * [Foreshadow](https://foreshadowattack.eu/) vulnerability page and papers
   * Intel: [Deep Dive: Intel Analysis of L1 Terminal Fault](https://software.intel.com/security-software-guidance/insights/deep-dive-intel-analysis-l1-terminal-fault) 
   * [Intel Microcode Guidance, August 8 2018](https://www.intel.com/content/dam/www/public/us/en/documents/sa00115-microcode-update-guidance.pdf)

**Comment by speed47** [comment]
Initial support has just been pushed to master (e942616)

**Comment by speed47** [comment]
Added detection of latest verified production microcodes for Intel, from their latest PDF, in fc1dffd.
I didn't want to implement such feature before, because by essence this kind of information will be out of date at some point, but as we yet got a new batch of microcodes, it'll probably help people understanding/checking why their CPU is still vulnerable, and will probably do more good than harm in the end.

(also partly addresses #205)

**Comment by knweiss** [comment]
@speed47 Thanks a lot for your fast response!

Two comments on this version (commit fc1dffd):

1. The L1TF vulnerability status is missing in the `CPU vulnerability to the speculative execution attack variants` list but then shown later  in detail:
```
[...]
* CPU vulnerability to the speculative execution attack variants
  * Vulnerable to Variant 1:  YES 
  * Vulnerable to Variant 2:  YES 
  * Vulnerable to Variant 3:  YES 
  * Vulnerable to Variant 3a:  YES 
  * Vulnerable to Variant 4:  YES 
                                  <==== missing L1TF status
[...]
CVE-2018-3615/3620/3646 [L1 terminal fault] aka 'Foreshadow & Foreshadow-NG'
> STATUS:  VULNERABLE  (your CPU is known to be vulnerable, and your kernel doesn't
report that it mitigates the issue, but more thorough mitigation checking by this script is
being worked on (check often for new versions!))
```
2. **If** the CPU's microcode is the latest, the following line is a little bit redundant:
```
CPU microcode is the latest known available version:  YES  (you have version 0xb00002e and latest known version is 0xb00002e)
```
How about this shorter output in this case?
```
CPU microcode is the latest known available version:  YES  (version 0xb00002e)
```

**Comment by mattvw** [comment]
It's looking like there won't be any new microcode updates after all, beyond what was released for variants 3a/4, as apparently the microcode updates already released for 3a/4 also mitigate Foreshadow/Foreshadow-NG/L1TF (at least the parts of it that need microcode updates).

So, as long as you have microcode/BIOS updates for 3a/4 applied, you just need OS (and maybe virtualization) updates (and also disable SMT/Hyperthreading too) to fully mitigate Foreshadow/Foreshadow-NG/L1TF

That's according to Intel and multiple OEMs:

https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00161.html (see under Recommendations)
https://www.dell.com/support/article/us/en/04/sln313494/speculative-execution-side-channel-vulnerabilities-cve-2018-3615-cve-2018-3620-and-cve-2018-3646-impact-on-dell-emc-poweredge-servers-storage-sc-ps-and-powervault-md-and-networking-products?lang=en
https://support.lenovo.com/us/en/solutions/LEN-24163
http://h22208.www2.hpe.com/eginfolib/securityalerts/Terminal%20Fault/L1-Terminal-Fault.html

It appears that the "new" microcode guidance PDF that Intel released is the same one they reference for the variant 3a/4 vulnerabilities (just with a newer date listed inside the PDF). In fact, the file is the same as the one still linked at for the 3a/4 Intel advisory: https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00115.html (The filename even says it's for INTEL-SA-00115, which is the Intel advisory number for variant 3a/4.)

**Comment by knweiss** [comment]
@mattvw This is also my understanding **regarding L1TF**.

However, there will be new microcode release (for whatever reason) and then this `spectre-meltdown-checker` output will become confusing.

(There are rumours of several speculative execution vulnerabilities still under embargo. I.e. we're not done yet...)

**Comment by mattvw** [comment]
@knweiss: Oh, yes, I definitely agree that there will be more coming soon...we won't be done with these for a long, long time!

I wasn't so much responding to your comment per se, but more just putting this out there for everyone (since it certainly wasn't clear to me initially). But I do agree with your # 2 point above. Sorry for the confusion!

**Comment by Matthew-Bradley** [comment]
If I recall, there were 5-6 unannounced ones back in may that intel wanted to keep under wraps while they worked on mitigations. Their estimated ETA (optimisitally) was august. That brings us to spectre 10 or 11, though I guess this counts as one of them, and 4/3a might count as one or two of them as well. Still, there have likely been many added to the list since then and it looks like probably only the stuff from really early this year/last year will be making it into silicon fixes in the immediate future.

Funny how this one involved disabling multithreading. I recall openBSD was disabling it as part of the TLBbleed mitigation, and I suppose they would have been informed about the microcode/OS patches for this one. Part of me wonders whether the mitigations might be related, or if they were both worked on by openBSD at the same time.

**Comment by knweiss** [comment]
@Matthew-Bradley The German website Heise (they also leaked the Spectre-NG news earlier this year) published a nice [Spectre-NG status table](https://www.heise.de/security/meldung/Spectre-NG-Foreshadow-gefaehrdet-Intel-Prozessoren-4137209.html). FWIW: The last line in the table reads (_"information on five additional Spectre-NG vulnerabilities is still missing"_).

**Comment by lesinigo** [comment]
The master branch (currently at 80e0db7) is possibly misreporting a patched FreeBSD as vulnerable to L1TF.

I've just updated a test server a couple of minutes ago and according to [FreeBSD-SA-18:09.l1tf](https://www.freebsd.org/security/advisories/FreeBSD-SA-18:09.l1tf.asc) it should be protected against L1TF.

This is the output I'm getting from the script:
```
Spectre and Meltdown mitigation detection tool v0.39+

Checking for vulnerabilities on current system
Kernel is FreeBSD 11.2-RELEASE-p2 FreeBSD 11.2-RELEASE-p2 #0: Tue Aug 14 21:45:40 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
CPU is Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

[....]

CVE-2018-3615/3620/3646 [L1 terminal fault] aka 'Foreshadow & Foreshadow-NG'
> STATUS:  VULNERABLE  (your CPU is known to be vulnerable, and your kernel doesn't report that it mitigates the issue, but more thorough mitigation checking by this script is being worked on (check often for new versions!))
```

**Comment by speed47** [comment]
OK, pushed the b44d2b5 on master, this should be the release candidate of next release, with proper L1TF support.
@lesinigo correct, I have a couple FreeBSD at home, will fix it before the release

**Comment by speed47** [comment]
v0.40 released with L1TF support for Linux and FreeBSD
