### ISSUE TITLE
Add support for checking CVE-2018-5407

### ISSUE THREAD

**Issue by bitwave** [speed47/spectre-meltdown-checker#261]
Ah new vulnerability was found: https://github.com/bbbrumley/portsmash

**Comment by speed47** [comment]
This seems to be a PoC of a timing attack on openssl, it has been fixed in the openssl code directly.
It does work only when hyperthreading (SMT) is enabled however. This is now widely accepted that if you're seeking maximum security, you should disable SMT altogether, including for future unknown vulnerabilities.
The scripts does require SMT to be disabled in `--paranoid` mode if the system is detected as running a hypervisor. I'll add a tiny modification to always consider there's a hypervisor in `--paranoid` mode to ensure the SMT check is always done regardless.
