### ISSUE TITLE
How intrusive is the script? (for production servers)

### ISSUE THREAD

**Issue by thbar** [speed47/spectre-meltdown-checker#293]
First, many thanks for releasing this tool!

I read the disclaimer & went through the code ; it seems that the script does various operations including `write_msr`, loading modules via `modprobe` etc.

This made me wonder: how safe it is to run on production servers? Is it going to, in some way, leave some state changed in the CPU or the disk? If that's the case, may a reboot be enough to cover that?

Thank you!

**Comment by onnozweers** [comment]
I occasionally run the script on a cluster of 150 Dell servers running Centos 7 (and some Centos 6), also this morning. No problem. Except that some of my servers need updates. 🐱

**Comment by speed47** [comment]
Efforts have been made to ensure that the script leaves the system at the same state it was before the script was run. For example, if kernel modules are needed and happen to not be loaded, the script loads them, and ensures to unload them before leaving. If some part of the system is different after running the script comparing to what it was before running it, then it's a bug and will be fixed.

It also doesn't do intrusive stuff such as calling home, or checking for updates. Such feature is not implemented and will never be (because I don't like intrusive scripts myself).

Now, as you're pointing out, it attempts to write on an MSR in two occasions. It's the most potentially "dangerous" thing it does (everything else is just "read", but unfortunately those two MSRs are write-only so the only way to check that they exist and work is attempting to write to them). But in that case, either the MSR doesn't exist, and it just does nothing, or it does exist, and is written to dozens/hundreds of time a second by the OS to mitigate specex issues anyway. If you don't want that to happen, you can use --no-hw to skip the hardware checking part, but the results might be inaccurate in that case.

Additionally, I can tell you that I had no report to date of this script crashing a system (which doesn't mean there's not a very exotic system out there that would behave weirdly!). Trying the script on a test system is always a wise thing to do however (as is anything you're projecting to do on your prod env!)

**Comment by thbar** [comment]
Thank you for the detailed response - much appreciated!
