### ISSUE TITLE
Misunderstanding the latest version of microcode

### ISSUE THREAD

**Issue by teoberi** [speed47/spectre-meltdown-checker#321]
spectre-meltdown-checker latest version (commit 59ad312)
> Spectre and Meltdown mitigation detection tool v0.42
> * CPU microcode is known to cause stability problems:  NO  (model 0x9e family 0x6 stepping 0x9 ucode 0xca cpuid 0x906e9)
>  * CPU microcode is the latest known available version:  YES  (latest version is 0xc6 dated 2019/08/14 according to local MCExtractor DB v130 - 2019/11/04)

I am confused the two lines do not understand each other.
`cat /proc/cpuinfo | grep microcode | uniq`
> microcode       : 0xca

The latest microcode version for my processor is: 0xca
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/blob/master/releasenote

**Comment by speed47** [comment]
This is because the script uses the MCE database as the source of truth for latest versions of microcodes (https://github.com/platomav/MCExtractor).
You can update the builtin database of the script from MCEdb using --update-builtin-mcedb. But in that case, MCEdb is just not up to date for your CPU. Now that Intel has their microcodes on github (!), the script should check both MCEdb and the Intel repo to get the latest versions info. I have to code this.

**Comment by speed47** [comment]
Can your confirm the intelfw branch detects the latest firmware for your CPU correctly?
(a direct link to the script under this branch is https://raw.githubusercontent.com/speed47/spectre-meltdown-checker/intelfw/spectre-meltdown-checker.sh )

**Comment by teoberi** [comment]
No, it does not detect the latest firmware for my processor.

>   * CPU microcode is known to cause stability problems:  NO  (model 0x9e family 0x6 stepping 0x9 ucode 0xca cpuid 0x906e9)
> * CPU microcode is the latest known available version:  YES  (latest version is 0xc6 dated 2019/08/14 according to local firmwares DB v130 - 2019/11/04)

**Comment by speed47** [comment]
This is because the script uses your local (outdated) copy of the firmwares 
db, good that's another bug to squash! ;)
You can `rm ~/.mcedb` and it'll then use the up to date builtin db version 
(--update-mcedb would do the trick too).
I'm fixing this properly (detection of outdated external db) in the next 
commit.

**Comment by teoberi** [comment]
The same thing I discovered!
If I deleted the .mcedb file the detection is OK!

>   * CPU microcode is the latest known available version:  YES  (latest version is 0xca dated 2019/10/03 according to builtin firmwares DB v130.20191104+i20191027)

If I recreate the database with the command:
`./spectre-meltdown-checker.sh --update-fwdb`
the result is

> Spectre and Meltdown mitigation detection tool v0.42
> Fetching MCE.db from the MCExtractor project... DONE
> Fetching Intel firmwares... DONE
> Extracting MCEdb data... OK MCExtractor database revision 130 dated 2019/11/04
> Integrating Intel firmwares data to db... DONE (version 20191027)
> Building local database... Error: near "ORDER": syntax error
> DONE (version 130.20191104+i20191027)

**Comment by speed47** [comment]
I''ve pushed a new version to the `intelfw` branch, fixing the stupid "ORDER BY" typo (it was meant to be a GROUP BY...), and added some logic to ignore local database if its version is older than the one from the script.
