### ISSUE TITLE
Script reports NOT VULNERABLE even when IBRS is supported partially

### ISSUE THREAD

**Issue by shadowlmd** [speed47/spectre-meltdown-checker#35]
I have an example where IBRS is enabled only for Kernel space, but script reports CVE-2017-5715 as not vulnerable. I believe, it should report "partially vulnerable" or something like that in such cases.

**Comment by speed47** [comment]
The script mainly focuses on the kernel indeed.
It has been a design choice to say "not vulnerable" if ibrs is at least enabled for the kernel. It might not be a good idea to enable it for all userspace because the perf impacts are not negligible at all. In any case, each sysadmin should test and take its decision about this, as it's mainly a security/perf tradeoff. However for kernel IBRS, it really should be enabled. This is why the script informs on the userland part, because you might want to see if the policy you have in mind is properly configured, but doesn't use it for the global status of the vuln.

**Comment by shadowlmd** [comment]
Got it, thank you!
