### ISSUE TITLE
i20200904?

### ISSUE THREAD

**Issue by teoberi** [speed47/spectre-meltdown-checker#379]
Where did you find i20200904?

**Comment by speed47** [comment]
To get the "i" date, the script integrates both MCExtractor data and Intel Microcodes GitHub repo data into a db, then gets the most recent Intel firmware and calls it the "i" date.

Usually the most recent Intel firmwares come from the Intel repo, so the "i" date is less or equal to the last Intel repo commit date. But this doesn't seem to be the case right now: the most recent Intel firmwares seem to come from the MCExtractor db, hence the misleading "i" date that, in fact, doesn't come from the Intel repo.

I'll modify the script so that the "i" date corresponds to the latest commit date of the Intel repo, it'll be less confusing that way.

**Comment by teoberi** [comment]
OK!
