### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by h3artbl33d** [speed47/spectre-meltdown-checker#399]
First of all, thank you for all the hard work - greatly appreciated!

The `spectre-meltdown-checker` script supports all Linux distributions and the majority of the BSD flavors. I did notice that OpenBSD isn't supported; is there a specific reason for it?

**Comment by speed47** [comment]
> First of all, thank you for all the hard work - greatly appreciated!

Thanks!

> The `spectre-meltdown-checker` script supports all Linux distributions and the majority of the BSD flavors. I did notice that OpenBSD isn't supported; is there a specific reason for it?

Yes, this is because what the script does is checking deeply in the OS (actually, the kernel) and in the CPU (by querying low-level information about mitigations support etc.), to give you the information about how these ranges of vulnerabilities apply to your system. The main target is Linux, but then FreeBSD was not a gigantic leap to implement because they have a compatbility layer : linprocfs, so most of the script worked out of the box, I just needed to add code to dig properly in the FreeBSD kernel (obviously, it has nothing to do with the Linux kernel). This is easier however because there are not bazillions of different versions / flavors / compilations / unofficial patches to the FreeBSD kernel, while this is the case for the Linux kernel, and is actually one of the main reasons this script exists.

Implementing support for other BSDs would mean reimplement everything (as there's no linprocfs), and also digging on each specific kernel. This would effectively be a completely different script, and it's the same amount of work that e.g. trying to port that to Windows, unfortunately.

**Comment by speed47** [comment]
This has been added as a [new entry](https://github.com/speed47/spectre-meltdown-checker/blob/master/FAQ.md#which-bsd-oses-are-supported) to the also brand new FAQ :)

Closing as a result, don't hesitate to reopen if needed!
