### ISSUE TITLE
Script in guest KVM

### ISSUE THREAD

**Issue by c0r3dump3d** [speed47/spectre-meltdown-checker#65]
![captura de pantalla de 2018-01-12 16-32-28](https://user-images.githubusercontent.com/5602401/34882246-3b99906c-f7b6-11e7-9bbf-9c7ff5b0ab1b.png)
Hi, I have run the script in a guest KVM/QEMU CentOS 7 machine, I have seen that all is ok but the variant 2 it's not corrected because I have not activated IBRS and I have noted that this is not posible because no microcode update for QEMU emulated CPU it's available. The question is if the script result is a false positive or not?

**Comment by speed47** [comment]
KVM/QEMU have a patch ready to be able to expose the MSR of the host to the guest (the new SPEC_CTRL MSR is what the microcode update makes available).
Do you know if you host microcode has been updated? If yes, and if you have a bleeding edge KVM, I would say the output is correct.
Can you also `grep spec_ctrl /proc/cpuinfo` ? I'm not sure the centos backports are exposing this flag or not, but it's another way to check if the microcode update is done

**Comment by c0r3dump3d** [comment]
Hi, yes, the host the microcode has been updated, with the libvirt and qemu packages and it's ok (see the image). 
![captura de pantalla_2018-01-13_11-32-15](https://user-images.githubusercontent.com/5602401/34905267-6e7d4ee8-f855-11e7-8c44-ea6d8fe5cd71.png)

But in the guest I haven't seen the flag  `spec_ctrl`, and no microcode update it's present:
![captura de pantalla_2018-01-13_11-36-27](https://user-images.githubusercontent.com/5602401/34905297-14f284b4-f856-11e7-91db-4b95a4f84cf5.png)

I don't undestand much but I think it's necesary a microcode update for the emulated QEMU CPU?

![captura de pantalla_2018-01-13_11-40-21](https://user-images.githubusercontent.com/5602401/34905324-905d7a14-f856-11e7-937d-17e51ec1a079.png)

**Comment by speed47** [comment]
An updated qemu/kvm is able to expose the microcode update (actually, the MSR that the microcode update adds) to the guest OS. So if you run the script within the guest OS, with a microcode-updated host and a qemu/kvm able to expose the MSR, you should see it as microcode-updated too.

Could you try the following command?
It's another way to test for the microcode update, and might be more accurate that the current way. This is derived from how the recent kernels take the decisions to enable IBRS themselves.

```bash
modprobe cpuid
dd if=/dev/cpu/0/cpuid bs=16 skip=7 iflag=skip_bytes count=1 2>/dev/null | od -x
```

**Comment by c0r3dump3d** [comment]
Hi, this the output of the comand:

```
# dd if=/dev/cpu/0/cpuid bs=16 skip=7 iflag=skip_bytes count=1 2>/dev/null | od -x
0000000 0121 0000 003f 01c0 003f 0000 0001 0000
0000020
```

**Comment by speed47** [comment]
Strange, MSR says it's good, CPUID says it's not.

I've pushed a test version on the `cpuid_spec_ctrl` branch. Could you try this version (with `-v -v`) on both your host and from inside the VM, and post the 2 results here?

Additionally, what version of qemu/kvm are you using?

**Comment by c0r3dump3d** [comment]
Hi, the execution in the host:
![captura de pantalla_2018-01-13_17-16-28](https://user-images.githubusercontent.com/5602401/34907860-906eb87c-f885-11e7-9ab6-2d0e0c51516b.png)

The execution in the guest:
![captura de pantalla_2018-01-13_17-18-12](https://user-images.githubusercontent.com/5602401/34907873-d44f8558-f885-11e7-93b0-8a6cd05b69c2.png)

The libvirt/qemu version:

![captura de pantalla_2018-01-13_17-20-15](https://user-images.githubusercontent.com/5602401/34907891-131a787e-f886-11e7-9512-1a729408fbfd.png)

![captura de pantalla_2018-01-13_17-21-35](https://user-images.githubusercontent.com/5602401/34907900-403758d6-f886-11e7-9c3a-f2fa59f4582e.png)

**Comment by speed47** [comment]
Thanks! So, this is getting more clear now.

For the Linux kernel to be able to use IBRS, you need two things: the `spec_ctrl` MSR, and a proper bit set in the CPUID info of your CPU. I thought that the availability of the MSR was enough, but it turns out by looking at the kernel sources that it's not: if the CPUID bit is not set, the kernel won't try to use the MSR.

In the qemu-kvm version you're using, which is a RedHat custom version, the MSR is correctly made available to the guest if the host has it (which your host does). However the CPUID bit is not set in the guest, even if the host has it. That's why you can't enable IBRS in your guest.

There are patches being worked on as I can see in the official qemu-devel mailing list, and those patches will make both available the MSR and the CPUID bit to the guest.

http://lists.nongnu.org/archive/html/qemu-devel/2018-01/threads.html

>[Qemu-devel] [PATCH 2/7] i386: Add support for SPEC_CTRL MSR, Eduardo Habkost, 2018/01/09
> [Qemu-devel] [PATCH 3/7] i386: Add spec-ctrl CPUID bit, Eduardo Habkost, 2018/01/09

So hopefully RedHat will catch up to those patches and will release i the following days a new qemu-kvm version that will make possible to use IBRS in the guest.

**Comment by c0r3dump3d** [comment]
Ok, thank you very much for your answer and work!!

**Comment by mattvw** [comment]
So, I had this exact same issue and I was able to resolve it using existing patches from Red Hat.

It turned out that the CPU Model for the VMs/guests have to be set to an -IBRS version of the CPU, in order for IBRS to be available to the VM. So, instead of just using Broadwell, you would use Broadwell-IBRS, etc. etc (any one of them will work, as shown below). You can also just select "Hypervisor Default" and it SHOULD use the IBRS version of the processor of the host machine (but I always selected an -IBRS one specifically, just to be sure).

Once I made that change, and then shut down the VM completely and started it back up, it showed as "NOT VULNERABLE" to all three variants (was showing as vulnerable to variant 2 before):

```
[root@ ~]# ./spectre-meltdown-checker.sh 
Spectre and Meltdown mitigation detection tool v0.31

Checking for vulnerabilities against running kernel Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64
CPU is Intel Core i7 9xx (Nehalem Core i7, IBRS update)

CVE-2017-5753 [bounds check bypass] aka 'Spectre Variant 1'
* Checking count of LFENCE opcodes in kernel:  YES 
> STATUS:  NOT VULNERABLE  (106 opcodes found, which is >= 70, heuristic to be improved when official patches become available)

CVE-2017-5715 [branch target injection] aka 'Spectre Variant 2'
* Mitigation 1
*   Hardware (CPU microcode) support for mitigation
*     The SPEC_CTRL MSR is available:  YES 
*     The SPEC_CTRL CPUID feature bit is set:  NO 
*   Kernel support for IBRS:  YES 
*   IBRS enabled for Kernel space:  YES 
*   IBRS enabled for User space:  NO 
* Mitigation 2
*   Kernel compiled with retpoline option:  NO 
*   Kernel compiled with a retpoline-aware compiler:  NO 
> STATUS:  NOT VULNERABLE  (IBRS mitigates the vulnerability)

CVE-2017-5754 [rogue data cache load] aka 'Meltdown' aka 'Variant 3'
* Kernel supports Page Table Isolation (PTI):  YES 
* PTI enabled and active:  YES 
* Checking if we're running under Xen PV (64 bits):  NO 
> STATUS:  NOT VULNERABLE  (PTI mitigates the vulnerability)

A false sense of security is worse than no security at all, see --disclaimer
```

This is using latest RHEL 7 packages like @c0r3dump3d was on both host and VM and Intel microcode updates for host machine.

Note: It still says NO for "The SPEC_CTRL CPUID feature bit is set" but then says the status is NOT VULNERABLE, with IBRS mitigation in place. So, it would appear that the SPEC_CTRL CPUID isn't fully necessary (however Red Hat did the backport).

Note, using a qemu CPU model for the VM (as it appears @c0r3dump3d is doing) won't work. You have to specify a real processor with the -IBRS indicated next to it.

Hope this helps!

**Comment by c0r3dump3d** [comment]
Thank you for the information. Apart from this, now I have seen that RedHat it's rolling back the microcode_ctl update, they have detected instabilities:

> The latest microcode_ctl and linux-firmware packages from Red Hat do not include resolutions to the CVE-2017-5715 (variant 2) exploit. Red Hat is no longer providing microcode to address Spectre, variant 2, due to instabilities introduced that are causing customer systems to not boot. The latest microcode_ctl and linux-firmware packages are reverting these unstable microprocessor firmware changes to versions that were known to be stable and well tested, released prior to the Spectre/Meltdown embargo lift date on Jan 3rd. Customers are advised to contact their silicon vendor to get the latest microcode for their particular processor.
