### ISSUE TITLE
Intel Atom vulnerable?

### ISSUE THREAD

**Issue by WordsOfMe** [speed47/spectre-meltdown-checker#78]
DId run the script on an Intel Atom 330 / 1.6GHz system, and it is shown vulnerable for all three CVEs. But as per Intel's list at https://security-center.intel.com/advisory.aspx?intelid=INTEL-SA-00088&languageid=en-fr the Atom 330 should not be affected (if I understood correctly).

I guess a check for non-vulnerable Atom processors has not been implemented yet?

**Comment by speed47** [comment]
Their list is not exhaustive (somebody here said that his CPU was not listed but the exploits were working).
However, for Atoms, it seems correct so I've added a check just for those. New Atoms are still vulnerable so I've just whitelisted the "old" Atoms.
Can you try the "atom" branch ? https://github.com/speed47/spectre-meltdown-checker/blob/atom/spectre-meltdown-checker.sh

**Comment by WordsOfMe** [comment]
Spectre 2 and Meltdown are now "not vulnerable", Spectre 1 is still "unknown" (readelf is not installed as this is a Sophos Home UTM). Plus, the comments "readelf missing" and "your vendor reported..." are not  shown now.
But anyway, great shell script!

**Comment by speed47** [comment]
I've added the Atom changes to the main version.
If you try it again, you should have the proper messages (your vendor reported...).
I'm closing this issue, but don't hesitate to reopen if the new main version doesn't work as you would expect!

**Comment by martian742** [comment]
I have 3 different used Atom systems on the way. Will test and report here as soon as I get them up & running. Thanks for your effort.

**Comment by speed47** [comment]
Thanks, reopening just to be sure I'm not missing your feedback

**Comment by WordsOfMe** [comment]
With today's version an Atom 330 is shown to be vulnerable to Spectre 1 and non-vulnerable to Spectre 2 and Meltdown. Shouldn't early Atoms be immune to Spectre 1 as well?

**Comment by martian742** [comment]
Same concern here, I ordered 3 different Atom based systems with 2 flavors of older Atoms: **N450**, **D2700**. Specifically to build some "more secure" systems that would be independent of the fixes the whole world is developing right now (not saying the fixes are or will be bad, they just may be insufficient forever on some CPUs).
I originally based my purchase decision on this list:    https://forum.level1techs.com/t/list-of-cpus-most-likely-immune-to-spectre/123128
The author claims there that basically all Atoms under the Bonnel microarchitecture are immune by design. But this is where my understanding starts to hang over the edge. 
From Wikipedia:
https://en.wikipedia.org/wiki/Bonnell_(microarchitecture)
"In the Bonnell microarchitecture, internal micro-ops can contain both a memory load and a memory store in connection with an ALU operation, thus being more similar to the x86 level and more powerful than the micro-ops used in previous designs.[3] This enables **relatively good performance with only two integer ALUs, and without any instruction reordering, speculative execution or register renaming**. The Bonnell microarchitecture therefore represents a partial revival of the principles used in earlier Intel designs such as **P5** and the **i486**, with the sole purpose of enhancing the performance per watt ratio."
I ended up choosing Atoms from the second (N450) and third generation (D2700), those employ hyper-threading for better multi-threaded performance. 
I don't know whether the second and third generation Atoms are as "vanilla" as the first generation **may have been.**

**Comment by speed47** [comment]
According to a kernel patch that just landed (not yet merged in any release), the CPUs that don't do speculative execution and hence are not vulnerable to any of the 3 variants are:

```
> +       { X86_VENDOR_INTEL,     6, INTEL_FAM6_ATOM_CEDARVIEW,   X86_FEATURE_ANY },
> +       { X86_VENDOR_INTEL,     6, INTEL_FAM6_ATOM_CLOVERVIEW,  X86_FEATURE_ANY },
> +       { X86_VENDOR_INTEL,     6, INTEL_FAM6_ATOM_LINCROFT,    X86_FEATURE_ANY },
> +       { X86_VENDOR_INTEL,     6, INTEL_FAM6_ATOM_PENWELL,     X86_FEATURE_ANY },
> +       { X86_VENDOR_INTEL,     6, INTEL_FAM6_ATOM_PINEVIEW,    X86_FEATURE_ANY },
> +       { X86_VENDOR_CENTAUR,   5 },
> +       { X86_VENDOR_INTEL,     5 },
> +       { X86_VENDOR_NSC,       5 },
> +       { X86_VENDOR_ANY,       4 },
```

N450 : Pineview => no specex
D2700 : Cedarview => no specex
330 : Diamondville but a kind of Pineview (model 0x1C) => no specex.

I'm adding the code that will detect that as future kernels will, in a branch that you'll be able to test soon.

**Comment by speed47** [comment]
Could you try the `refacto` branch ? I would be interested to get the results from some Atom owners, to be sure that it works correctly.

**Comment by WordsOfMe** [comment]
With the current refacto branch I get a "non vulnerable" for all CVEs on an Atom 330 board (family 6, model 28=0x1c: Diamondville / Pineview).
Seems OK now, thanks!

**Comment by speed47** [comment]
Thanks, this has been merged to master, closing.
