### ISSUE TITLE
[cosmetic] --no-sysfs is required for verbosity

### ISSUE THREAD

**Issue by kuzetsa** [speed47/spectre-meltdown-checker#96]
The following verbosity is lost without --no-sysfs

```
* Mitigation 1
*   Hardware (CPU microcode) support for mitigation
*     The SPEC_CTRL MSR is available:  NO 
*     The SPEC_CTRL CPUID feature bit is set:  NO 
*   Kernel support for IBRS:  NO 
*   IBRS enabled for Kernel space:  NO 
*   IBRS enabled for User space:  NO 
* Mitigation 2
*   Kernel compiled with retpoline option:  YES 
*   Kernel compiled with a retpoline-aware compiler:  NO  

* Kernel supports Page Table Isolation (PTI):  YES 
* PTI enabled and active:  YES 
````
---
**Note:** Possibly this output is worse verbosity due to naive test of
/sys/kernel/**debug/**.*whatever*/ &nbsp; even when /proc/config.gz is showing:

```
# CONFIG_DEBUG_FS is not set
```

(*edited: earlier reference to:* ~CONFIG_DEBUG_KERNEL~ *was improper*)

**Comment by kuzetsa** [comment]
```
[ /usr/src/linux/lib/Kconfig.debug ]
(help text)

debugfs is a virtual file system that kernel developers use to put
debugging files into.  Enable this option to be able to read and
write to these files.

For detailed documentation on the debugfs API, see
Documentation/filesystems/.

If unsure, say N.
```

**Emphasis:** If unsure, say N.

A naive test assuming this will be enabled is prone to failure.

**Comment by speed47** [comment]
Newer kernels having some or all of the mitigations are starting to export the status of the mitigation within the kernel debugfs hierarchy. This is the best way to know if you're safe or not, because the information comes from the kernel directly. Without it, the information has to be inferred from other data (all the stuff that the script does if the debug hierarchy is not there).
It can still be interesting to see what the script infers even if the debugfs hierarchy is present and this is why the `--no-sysfs` switch is made for (true, it should have been named `--no-debugfs`).
I know that, regardless of the fact that the kernel is recent enough or not to be able to export this information thru debugfs, CONFIG_DEBUG_FS might or might not be available. But does the script fail in that case ? Because it shouldn't and default to relying on inferring the data.

**Comment by kuzetsa** [comment]
got a [waiting-feedback] email. I'll try to be thorough.

I can't attest to other kernels which do(n't) export info via debugfs.
I maintain sys-kernel/ck-sources package for gentoo, so here's this:
```
$ cat /proc/version 
Linux version 4.14.14-ck (kuzetsa@soyokaze) (gcc version 6.4.0 (Gentoo 6.4.0-r1 p1.3)) #1 SMP PREEMPT Wed Jan 17 20:08:46 EST 2018
```
Because this is going to be vendor-dependent, here's the case I'm most familiar with:  
For gentoo specifically, it's up to the user to decide if they want to use a pregenerated config which may or may not be downloaded from a third party, or made by a or tool which picks settings, or the user might hand-configure before building their own kernel without any guided assistance (*for example: some will borrow a kernel config from a different vendor and use that as a starting point, or use the kernel from the livcd/dvd/usb boot media, etc. Nearly any kernel config works as a starting point, including "defconfig".*)

For anyone (*gentoo or otherwise*) building their own kernel, the in-tree 'menuconfig' utility which comes with kernel source code (*including straight from kernel.org*) always explains debugfs the same way:
```
If unsure, say N.
```
---
I'm unsure what you mean about: [does the script fail in that case?]

The meltdown checker script does seem to know how to consume /proc/config.gz (*unpacking, at least. I haven't checked very deeply*), yet doesn't test for the CONFIG_DEBUG_FS option:

```
# CONFIG_DEBUG_FS is not set
```

Testing for debugfs seems more correct than checking for sysfs. Just seems like a minor oversight. I'm not sure about the specific branching logic / line(s) of script with relevant if-then-else, etc. which produces this specific behavior for output to be more/less verbose while (not) using --no-sysfs

puzzling trivia about debugfs:

debugfs is enabled by [ make defconfig ] - this is an ironic contradiction, and  
is in disagreement with help text in: [ kernel_source_tree/lib/Kconfig.debug ]  
(*kernel_source_tree/lib/Kconfig.debug contains the help text for menuconfig*)

**Comment by speed47** [comment]
Thanks for your reply.
About the "waiting-feedback" e-mail, no worries, this is just me trying to tidy up the issues to be sure I'm not missing any. I didn't know it was sending an e-mail when this tag was set however.

In any case, I think I understand better your issue now. The script has two "modes" of operation:
- The first one is the one you call the "verbose" one, which tries to fetch as much information possible from the kernel and CPU to try to determine if these are vulnerable or not, and check if the mitigations seem to be in place or not.
- The second one is the "debugfs" oriented one, which works only if debugfs is available (it's not always the case as you pointed out) and also only if the kernel is recent enough to export vulnerability information through debugfs. We don't need to check for CONFIG_DEBUGFS because if /sys/kernel/debug is not there, and we fail in inserting the module (in case it's not compiled in), and the mount -t debugfs fails, we know for a fact that it's not there anyway (or it's there but for some reason doesn't work correctly).

The "debugfs" mode is preferred when available because the information is then 100% accurate, as it directly comes from the kernel. There's no guessing involved at all. There's also not much verbosity because there's almost nothing to be verbose about: we just print what the kernel tells us.
The first mode however, is a lot more verbose because you can see the different steps of information gathered that, when added to each other, come to a conclusion about a vulnerable/non vulnerable status.

As you're using gentoo, I suppose you just compiled a new kernel, so you have the debugfs hierarchy available with the vulnerability info inside it, and that's why you get the second mode of operation. It's not really more verbose even if you add -v because there's nothing to be verbose about. You can force it to the first mode with --no-sysfs however (but the information might be slightly less accurate).

I think I'll change something: either run the first mode only when debugfs or the vuln info from kernel is not there (as it's the case today), or run the first mode *and* the second mode when it's there, but only rely on the information from the second mode to determine the status. This way you get the "verbosity" you were expecting, but also with the guarantee of a 100% accurate result.

**Comment by kuzetsa** [comment]
I like having information, so I wasn't sure about the correct behavior when disabling a feature  resulted in more information. It seemed counter-intuitive, so thanks for having a look at it.

**Comment by speed47** [comment]
I've made some modifications to the script, so that, even if the /sys interface is available, other details are still printed. This is in the `ibpb` branch, that you can already test, and which should be merged in master soon.

**Comment by kuzetsa** [comment]
The version I originally tested was never this verbose.  
This change is well done, but I noticed some wrapping in the output (including output of --help isn't wrapped to 72 or 80 columns. (*while not everyone has need for large fonts and/or low column counts, this also doesn't mean everyone prefers or uses a high column count workflow. Basically, it looks a bit strange to have indented text in the output which wraps in awkward places*)

I can send a PR with proposed wrapping fixes if you like.

**Comment by speed47** [comment]
Thanks for the proposition, but I don't want to enforce a 72 or 80 chars max per line rule, because that would make the output more difficult to understand in some cases. I'm still trying to avoid lines that are really too long, though!
Closing this issue as the original problem is resolved. Trying to tidy up the issue list ;)
