### ISSUE TITLE
Atom N270

### ISSUE THREAD

**Issue by pit65** [speed47/spectre-meltdown-checker#97]
The script tells that I am vulnerable?

Imposible.

**Comment by speed47** [comment]
Could I have the output of `grep model /proc/cpuinfo` on your system?
Detection for a N270 has been adjusted since issue #90, they were misdetected because apparently the name "Atom" doesn't appear in the output, but maybe it does for some versions? Getting the output on your system would help a lot!

**Comment by pit65** [comment]
[12:09:02 --> pi in ~]$ grep model /proc/cpuinfo
model : 28
model name : Intel(R) Atom(TM) CPU N270 @ 1.60GHz
model : 28
model name : Intel(R) Atom(TM) CPU N270 @ 1.60GHz

**Comment by speed47** [comment]
Thanks. Some N270s appear with this other variation: `model name : Genuine Intel(R) CPU N270 @ 1.60GHz`.
So, implemented both. Latest version should work for you.

**Comment by speed47** [comment]
Closing this issue. Please reopen if, after testing the new version, it still doesn't work for you.
Thanks!
