### ISSUE TITLE
Possible false result

### ISSUE THREAD

**Issue by jtreen** [speed47/spectre-meltdown-checker#98]
After having applied every update (inncluding BIOS) that I'm aware of these are now my results:

![tool](https://user-images.githubusercontent.com/16100659/35111790-fb88bfd0-fc73-11e7-993c-cc622f04cd03.png)

However, this [Spectre POC from crozone](https://github.com/crozone/SpectrePoC) still executes successfully.

Is the tool falsely reporting that I am not vulnerable, or is the POC no good?

**Comment by speed47** [comment]
This POC attacks userspace from userspace, to test mitigation for this case, you should try to enable IBRS for user space too (the script correctly reports that IBRS is not enabled for user space in your case).

This is usually not enabled by default because it has a medium/high performance impact, so this has to be your choice to enable it or not (compromise of security vs performance).

On most distros, enabling IBRS for kernel and userspace until next reboot is done by `echo 2 > /sys/kernel/debug/ibrs_enabled`

**Comment by jtreen** [comment]
Thanks for that. I think it is misleading for the tool to state "NOT VULNERABLE" to variant 2 when it is in fact vulnerable under some conditions. Or perhaps at least "IBRS mitigates the vulnerability" could be clarified.

Do you know the procedure for enabling IBRS for userspace in Ubuntu (16.04)? The command you suggested does not work as I can't write to /sys (even as root) and that file appears to not exist anyway. Google doesn't suggest much. I would like to enable this protection, at least until retpoline makes it into the Ubuntu kernels.

**Comment by speed47** [comment]
I can add some test near the "not vulnerable" status to clarify that indeed.

For Ubuntu, it might be in the `/proc/sys/kernel/ibrs_enabled` file if you have it (there are different locations with different distributors/distros)

**Comment by jtreen** [comment]
Great, thanks! The tool now reports IBRS enabled for both user space and kernel space. However, the POC still executes successfully :/.

**Comment by speed47** [comment]
I'm not sure the PoC is a proper way to detect that Variant 2 is mitigated for the kernel: the PoC you're linking is actually attacking itself, this just shows that your CPU is indeed vulnerable to think kind of attack.

When the mitigation is in place, it means that the kernel no longer can be attacked, but it doesn't fix the underlying problem: the CPU is vulnerable, and all we can do is apply mitigations (that don't fix the problem because the problem is in the silicium, but at least limits the risks).
